### ISSUE TITLE
Output of SIAC_S2?

### ISSUE THREAD

**Issue by Diego-Barbulo** [MarcYin/SIAC#11]
Hi,

I am having some trouble implementing the code. I am trying to atmospherically correct a Sentinel 2 (TOA) .tif file via "from SIAC import SIAC_S2 SIAC_S2('/directory/where/I/have/stored/the/S2/data')". The code runs seamlessly, but there is no output. Where is the SIAC_S2 function storing the output BOA image?

Thank you for your time,
Diego

**Comment by MarcYin** [comment]
Sorry for the late response, the outputs are in the original sentinel 2 `IMG_DATA` folder, where you will find the surface reflectance and their uncertainties with names of `_sur.tif` and `_sur_unc.tif` respectively.
