### ISSUE TITLE
Stale links for supporting data

### ISSUE THREAD

**Issue by mfreem02** [MarcYin/SIAC#13]
I am attempting to use SIAC to process Sentinel-2 data. I am getting an error in reproject.py that I think is caused by the code trying to download a global DEM from:

http://www2.geog.ucl.ac.uk/~ucfafyi/eles/global_dem.vrt

This link is not working for me. Can it be fixed? If not, is there another place that the same file can be obtained?

I think it may need something from here too:

http://www2.geog.ucl.ac.uk/~ucfafyi/cams/

Thanks in advance.

-M

**Comment by MarcYin** [comment]
This has been fixed and please use the new version.
