### ISSUE TITLE
Error in atmo_solver

### ISSUE THREAD

**Issue by nbennasr** [MarcYin/SIAC#21]
Could you please take a look at this error:
"exc_info": "Traceback (most recent call last):\n  File \"/opt/s2gm/modules/SIAC/SIAC/SIAC_S2.py\", line 48, in SIAC_S2\n    aero_atmo = do_correction(*ret)\n  File \"/opt/s2gm/modules/SIAC/SIAC/SIAC_S2.py\", line 208, in do_correction\n    example_file = aero._solving(cloud_mask)\n  File \"/opt/s2gm/modules/SIAC/SIAC/the_aerosol.py\", line 1253, in _solving\n    ret = self.aero._multi_grid_solver()\n  File \"/opt/s2gm/modules/SIAC/SIAC/atmo_solver.py\", line 272, in _multi_grid_solver\n    psolve = optimize.minimize(self._cost, p0, jac=True, bounds = bounds, method='L-BFGS-B', options={'disp': False, 'maxcor': mc, 'gtol': 1e-02, 'ftol': ftol, 'maxfun': mf, 'maxiter': mi})\n  File \"/usr/local/lib/python3.10/dist-packages/scipy/optimize/_minimize.py\", line 696, in minimize\n    res = _minimize_lbfgsb(fun, x0, args, jac, bounds,\n  File \"/usr/local/lib/python3.10/distpackages/scipy/optimize/_lbfgsb_py.py\", line 305, in _minimize_lbfgsb\n    sf = _prepare_scalar_function(fun, x0, jac=jac, args=args, epsilon=eps,\n  File \"/usr/local/lib/python3.10/distpackages/scipy/optimize/_optimize.py\", line 332, in _prepare_scalar_function\n    sf = ScalarFunction(fun, x0, args, grad, hess,\n  File \"/usr/local/lib/python3.10/distpackages/scipy/optimize/_differentiable_functions.py\", line 158, in __init__\n    self._update_fun()\n  File \"/usr/local/lib/python3.10/dist-packages/scipy/optimize/_differentiable_functions.py\", line 251, in _update_fun\n    self._update_fun_impl()\n  File \"/usr/local/lib/python3.10/dist-packages/scipy/optimize/_differentiable_functions.py\", line 155, in update_fun\n    self.f = fun_wrapped(self.x)\n  File \"/usr/local/lib/python3.10/distpackages/scipy/optimize/_differentiable_functions.py\", line 137, in fun_wrapped\n    fx = fun(np.copy(x), *args)\n  File \"/usr/local/lib/python3.10/dist-packages/scipy/optimize/_optimize.py\", line 76, in __call__\n    self._compute_if_needed(x, *args)\n  File \"/usr/local/lib/python3.10/dist-packages/scipy/optimize/_optimize.py\", line 70, in _compute_if_needed\n    fg = self.fun(x, *args)\n  File \"/opt/s2gm/modules/SIAC/SIAC/atmo_solver.py\", line 505, in _cost\n    obs_J, obs_J_       = self._obs_cost_test(p)\n  File \"/opt/s2gm/modules/SIAC/SIAC/atmo_solver.py\", line 387, in _obs_cost_test\n    J_[:, self.Hx, self.Hy] = dJ\nValueError: shape mismatch: value array of shape (2,6) could not be broadcast to indexing result of shape (2,1)"

I get the same error for the images below:
{
  "60cd5041-41c2-4ebf-856a-6ee4c68c95dd": "S2A_MSIL1C_20230212T101131_N0509_R022_T33TVM_20230212T121022",
  "d794bf62-3a39-41af-a39b-aad8d4ef21f4": "S2B_MSIL1C_20221229T101329_N0509_R022_T32TQT_20221229T105025",
  "475548d3-8940-4fd5-b2ce-7ff50edd4616": "S2A_MSIL1C_20230116T102351_N0509_R065_T32TQT_20230116T122014",
  "39c24def-f636-4a5b-99a2-e41f2120e33f": "S2B_MSIL1C_20221226T100329_N0509_R122_T33TUN_20221226T103812",
  "feeb703e-0e1c-47c9-aa5e-1128e2e03454": "S2A_MSIL1C_20230103T101411_N0509_R022_T32TPS_20230103T121034"
}

**Comment by MarcYin** [comment]
This has been resolved.
