### ISSUE TITLE
nodata in B02 generated by SIAC_S2

### ISSUE THREAD

**Issue by nbennasr** [MarcYin/SIAC#22]
@MarcYin  Could you please check why B02_sur.tif contain nodata (red area) while the original band B02.jp2 does not?
the B02_nbar_sza_temporal_avg.tif contains nodata as well.

I uploaded the output of SIAC and the zip file [here](https://ftp.luxcarta.online/T33TVN.zip)

B02_sur.tif
![image](https://github.com/MarcYin/SIAC/assets/116064092/af0d0fbf-5af5-4296-9710-9090fdfba482)

B02.jp2
![image](https://github.com/MarcYin/SIAC/assets/116064092/772d9faa-c41d-488b-9298-878b5d6ecf45)

**Comment by MarcYin** [comment]
Hi,

This is related to the shadow (from the cloud or maintains) in the image, which cause reflectance to be native after atmospheric correction. However, the reflectance should be positive, so those pixels with negative values are masked out in the surface reflectance and should not be used for analysis.

Thanks.

**Comment by nbennasr** [comment]
Thank you for your quick reply
In this case all spectral bands should have nodata in the same areas, but B02 have nodata more than other bands.

**Comment by MarcYin** [comment]
Yes, that's correct, as the shorter the wavelength (B02), the larger the effect of AC on the reflectance. So you would have larger portion of darkest pixels being negative after AC.
