### ISSUE TITLE
Stange pixels after applying NBAR

### ISSUE THREAD

**Issue by nbennasr** [MarcYin/SIAC#24]
@MarcYin Could you please take a look at the SIAC output [here](https://ftp.luxcarta.online/S2A_MSIL1C_20220808T142721_N0400_R053_T20MRD_20220808T192835.SAFE.zip) where a strange pixels appear after applying NBAR.

RGB after SIAC:

![image](https://github.com/MarcYin/SIAC/assets/116064092/9f65b279-f211-48ce-90d3-4df7c9aacc79)

![image](https://github.com/MarcYin/SIAC/assets/116064092/114e6501-5cff-415e-9b86-6c1086b24548)

RGB after NBAR:

![image](https://github.com/MarcYin/SIAC/assets/116064092/023b260b-e001-455e-92ff-341973b64a8b)

![image](https://github.com/MarcYin/SIAC/assets/116064092/3bd4936f-9567-4d63-96d5-a9fc7815ff46)

**Comment by MarcYin** [comment]
This is caused by bad quality BRDF prior (mostly very dark surface). It has been identified and filled with values from the surrounding pixels and stored in the c_factor_mask file for each band.

Thanks.

**Comment by nbennasr** [comment]
Thank you!
