### ISSUE TITLE
IndexError in s2_pre_processing

### ISSUE THREAD

**Issue by nbennasr** [MarcYin/SIAC#28]
Hi @MarcYin,
Could you please look at the issue below that you can reproduce with flowing images:
[
  {
    id: 15126a95-ccff-4041-af9f-4e98853d3cc4,
    name: S2A_MSIL1C_20230721T103631_N0509_R008_T32TLS_20230721T160153
  },
 {
    id: 7b08399f-c9fd-4b83-b02c-4e05a074ec34,
    name: S2A_MSIL1C_20230731T103631_N0509_R008_T32TLS_20230731T173811
  }
]

Traceback (most recent call last):
  File \"/opt/s2gm/siac/src/siac_pipeline.py\", line 152, in siac_pipeline
  SIAC_S2(
  File \"/opt/s2gm/modules/SIAC/SIAC/SIAC_S2.py\", line 45, in SIAC_S2
  rets = s2_pre_processing(s2_t, cams_dir, global_dem)
  File \"/opt/s2gm/modules/SIAC/SIAC/s2_preprocessing.py\", line 182, in s2_pre_processing
  processing_baseline = PRODUCT_ID.split('_')[3][1:]
  IndexError: list index out of range

**Comment by MarcYin** [comment]
This has been fixed in new commit: https://github.com/MarcYin/SIAC/commit/794e572e635f2cf8f2255368b2b019a52bdd1c41

**Comment by nbennasr** [comment]
@MarcYin Thank you!
