### ISSUE TITLE
Missing CAMS file

### ISSUE THREAD

**Issue by nbennasr** [MarcYin/SIAC#29]
Hi @MarcYin,
Could you please check from your side these two images where I get the same error below:
[
  {
    id: 9a27cd2e-d269-4ce4-9958-44de9d96006d,
    name: S2B_MSIL1C_20230809T101609_N0509_R065_T32TNN_20230809T122143
  },
  {
    id: ce94d977-f54a-4273-9fec-8c98fb06dff1,
    name: S2B_MSIL1C_20230806T100559_N0509_R022_T32TNN_20230806T121212
  }
]

Traceback (most recent call last):
  File \"/opt/s2gm/siac/src/siac_pipeline.py\", line 152, in siac_pipeline
    SIAC_S2(\n  File \"/opt/s2gm/modules/SIAC/SIAC/SIAC_S2.py\", line 49, in SIAC_S2
    aero_atmo = do_correction(*ret)\n  File \"/opt/s2gm/modules/SIAC/SIAC/SIAC_S2.py\", line 119, in do_correction
    subset_file = subset_atmos(raster_file, cams_file)
  File \"/opt/s2gm/modules/SIAC/SIAC/prepare_aux.py\", line 160, in subset_atmos
    subset_raster(raster_file, atmo_file, out_raster_file, xRes=27450, yRes=27450)
  File "/opt/s2gm/modules/SIAC/SIAC/prepare_aux.py\", line 102, in subset_raster
    no_data_value = g.GetRasterBand(1).GetNoDataValue()\nAttributeError: 'NoneType' object has no attribute 'GetRasterBand'

![Capture d'écran 2023-10-05 091337](https://github.com/MarcYin/SIAC/assets/116064092/eab6e73f-2af1-40b2-86a6-c5d518694ca0)

Logs with DEBUG level:

![Capture d'écran 2023-10-05 094917](https://github.com/MarcYin/SIAC/assets/116064092/d5ffcdfe-a78b-4e3d-a19a-07902852d63d)

**Comment by MarcYin** [comment]
Updating the CAMS files from our server.
