### ISSUE TITLE
no-data in all bands after applying NBAR

### ISSUE THREAD

**Issue by nbennasr** [MarcYin/SIAC#30]
Hi @MarcYin,
Could you please take a look at these images where I get no-data in all bands after applying NBAR:
{
  '5e4c257c-89af-4949-99df-7875377cf426': 'S2B_MSIL1C_20220821T233649_N0400_R030_T01WDM_20220821T235303',
  '805643fe-1232-480f-8f76-14db4fb225f2': 'S2A_MSIL1C_20220813T232651_N0400_R130_T01WDM_20220814T005334',

  '768c9c4a-935d-4ed7-afb7-b774e223089d': 'S2A_MSIL1C_20220629T072631_N0400_R049_T37MFR_20220629T092648', 
  'a9699419-770e-40d5-82cb-77f5ffaf7fb8': 'S2A_MSIL1C_20220626T071631_N0400_R006_T37MFR_20220626T090942',
  '9e390750-bb1d-4eb5-ac80-b56eb9d21242': 'S2B_MSIL1C_20220621T071619_N0400_R006_T37MFR_20220621T091426',
  '47035897-5ec0-4c1d-8fcb-f5dd84db4a57': 'S2A_MSIL1C_20220616T071631_N0400_R006_T37MFR_20220616T091957',
  '8ce5dc99-bf95-4c34-9023-0bea1d820fcc': 'S2B_MSIL1C_20220614T072619_N0400_R049_T37MFR_20220614T092421',
  '9e79d873-9a3f-4165-8a26-4c3287462560': 'S2A_MSIL1C_20220609T072621_N0400_R049_T37MFR_20220609T092435',
  '1f2c9b0c-045c-47d1-bfaf-d0d6b9d72df9': 'S2B_MSIL1C_20220601T071619_N0400_R006_T37MFR_20220601T093802',
  'c282c5d5-1240-4f8b-8838-5128751d7ec8': 'S2A_MSIL1C_20220530T072621_N0400_R049_T37MFR_20220530T092025',
  '01f9bf28-f6d4-4456-b0c3-49dfa53aa1d5': 'S2A_MSIL1C_20220527T071621_N0400_R006_T37MFR_20220527T091047',
  '1d605b7e-fdc2-408c-b815-2c229c280184': 'S2B_MSIL1C_20220525T072619_N0400_R049_T37MFR_20220525T092234',
  '0378072c-d272-45b3-b2c4-44c9738785c2': 'S2B_MSIL1C_20220522T071619_N0400_R006_T37MFR_20220522T092404',
  '34d95bee-f667-4507-9539-44d24eb331a4': 'S2A_MSIL1C_20220520T072621_N0400_R049_T37MFR_20220520T092224'
}

Thank you!

**Comment by MarcYin** [comment]
This is due to the entire S2 image being water causing nan values for the c factor. This has been fixed by fill the c_factor values to 1 in 3d97a53e8f2d80c7a72ee05b892781a9aae63f5e, which essentially no NBAR normalisation due to the lack of BRDF information.

**Comment by nbennasr** [comment]
Thank you @MarcYin !
