### ISSUE TITLE
no-data in the SIAC output

### ISSUE THREAD

**Issue by nbennasr** [MarcYin/SIAC#31]
Hi @MarcYin,

Could you please put zero instead of nodata (-9999) in dark area because we should not have no-data in a BrightEarth mosaic.

Below an example of BrightEarth SIAC mosaic with no-data:
the two selected images are:
{
'28005872-f735-415f-822b-c8d3a50b0077': 'S2A_MSIL1C_20200818T105031_N0500_R051_T31UCR_20230320T061717',
 '672e0209-5d51-46c1-9369-0fe0b199fc61': 'S2A_MSIL1C_20200811T105631_N0500_R094_T31UCR_20230425T134117'
}

![image](https://github.com/MarcYin/SIAC/assets/116064092/55042ff2-69f0-45cf-bd67-bbd54ff51b75)

**Comment by MarcYin** [comment]
This should be fixed with the [new commit](https://github.com/MarcYin/SIAC/commit/253248257c7940df70144032b39342c9c0219340)

**Comment by nbennasr** [comment]
Thank you!
